# development stage
FROM node:lts-alpine AS dev

WORKDIR /app

COPY frontend/package.json ./
RUN npm install

COPY frontend/ .

CMD ["npm", "run", "dev"]

# build stage
FROM node:lts-alpine AS build

WORKDIR /app

COPY frontend/package.json ./
RUN npm install

COPY frontend/ .

RUN npm run build

# production stage
FROM nginx:alpine AS prod

COPY --from=build /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
