# development stage
FROM node:lts-alpine AS dev

WORKDIR /app

COPY frontend/package.json ./
RUN npm install

COPY frontend/ .

CMD ["npm", "run", "start"]

# build stage
FROM node:25-alpine AS build

WORKDIR /app

COPY frontend/package.json ./
RUN npm install

COPY frontend/ .

RUN npm run build

# production stage
FROM nginx:alpine AS prod

COPY --from=build /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]

