# development stage
FROM node:lts-alpine AS dev

WORKDIR /app

COPY backend/package.json ./
RUN npm install

COPY backend/ .

CMD ["npm", "run", "dev"]

# production stage
FROM node:lts-alpine AS prod

WORKDIR /app

COPY backend/package.json ./
RUN npm install

COPY backend/ .

CMD ["npm", "start"]
